### PR TITLE
Use monospage font for code blocks

### LINKED ISSUE #29: Consider using a fixed width font in code snippets
I think it helps make the code more readable.

### PR DESCRIPTION
**Pull request by ghoshbishakh**
fixes #29

### CODE REVIEW

**Comment by arokem** [comment]
Would it be worth applying this also to the output blocks? For example, in the SNR example the block of printed text at the bottom ("SNR for the b=0 image is : ‘‘42.0695455758’‘" etc.) should probably look different than the text in the explanations.

**Comment by ghoshbishakh** [comment]
@arokem yes that will probably be more clear. But the problem is that in that case the output needs to be distinguished somehow in the rst files, else they are simple paragraphs.

I am increasing the line height and paragraph spacing as it seems to have a better effect on readability.

**Comment by arokem** [comment]
Yes - it would be good to go through the rst examples and find these blocks and indent them.

**Comment by ghoshbishakh** [comment]
@arokem great.. I will start indenting them.

**Comment by Garyfallidis** [comment]
Indentation in another PR in nipy/dipy. Thx!

**Pull request merged**
