### PR TITLE
Handle exceptions in tutorials and documentation rendering

### PR DESCRIPTION
**Pull request by ghoshbishakh**

### CODE REVIEW

**Comment by jchoude** [comment]
Looks good from just looking at the code... Can you just tell me what would render if the documentation failed to build?

**Comment by ghoshbishakh** [comment]
@jchoude actually it will check the tutorials page and if that contains no links then it will give a blank tutorials page

**Comment by ghoshbishakh** [comment]
http://dipy.herokuapp.com/documentation/0.12.0.dev/examples_index/

It checks this page actually and as you can see Workflows (NEW) tutorials are not built as I had not built them so they are excluded in the tutorials page

**Comment by jchoude** [comment]
Ok. I think it would be helpful for the end user to maybe display just a quick message like: "Oups, there was a problem rendering the tutorials. Please contact the Dipy team to resolve this issue..."

**Comment by ghoshbishakh** [comment]
@jchoude ya that reminded me of friendly 404. Do you have any ideas?

**Comment by jchoude** [comment]
For a general 404, I tend to prefer something "funny". COuld be a screenshot of some streamlines, with a message like:

"Sorry, our brains seem to be busy and couldn't find this page. Go back home?"

or something like that, but I'm open.

As for the tutorials not rendering, currently, it's true that when we click on the Workflows link, nothing happens. I think the end user might wonder why nothing shows up. I think it would be helpful to display a warning message in this case, and maybe ask them to report it, so that we can fix it if we missed it during review.

**Comment by ghoshbishakh** [comment]
@jchoude yes empty sections can give a warning. I will look into it.

**Pull request merged**
